### ISSUE TITLE
ICachePoolFactory create method return type

### ISSUE THREAD

**Issue by flokixdev** [contributte/psr6-caching#1]
I think that **\Contributte\Psr6\ICachePoolFactory** create(...) method should have return type: **\Psr\Cache\CacheItemPoolInterface (interface)**
instead of
**\Contributte\Psr6\CachePool (concrete implementation)**

Am I right?

**Context:**
My actual use case is that I want to use contributte/psr6-caching for a package that is used in Nette and in Symfony apps. So I need to create a new CachePoolFactory in my app that handles the Symfony case, however, I cannot inject ICachePoolFactory because its actual return type Contributte\Psr6\CachePool depends on Nette implementation.

**Comment by f3l1x** [comment]
Yup, it appears it should. Could you please prepare PR?
