### ISSUE TITLE
Create stable version v1.0.0

### ISSUE THREAD

**Issue by janbarasek** [contributte/psr6-caching#4]
Hello,

can you create the first production version with the current master, please?

I really want to fix my dependency:

![Snímek obrazovky 2020-10-10 v 20 33 02](https://user-images.githubusercontent.com/4738758/95662510-ccae1680-0b37-11eb-9fc2-ce5a00ea99af.png)

Thanks.

**Comment by f3l1x** [comment]
Yup, will do.

**Comment by f3l1x** [comment]
v0.2.0 bumped https://github.com/contributte/psr6-caching/releases/tag/v0.2.0
