### ISSUE TITLE
Allow use of nette/caching 3.1

### ISSUE THREAD

**Issue by hubipe** [contributte/psr6-caching#7]
Hi,
is it possible to allow use of newly released nette/caching 3.1? The package version constraint towards nette/caching in composer is set to ~3.0.0, which does not allow usage of 3.1 branch, but in readme the library claims to be compatible with Nette 3.0+.
I propose to update the dependency to ~3.0, so allowed is all future versions of nette/caching up until version 4.0.

Thank you for consideration

**Comment by f3l1x** [comment]
Resolved in #8
